version: "3.8"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://localhost:27017/cloud" # replace "mydatabase" with your database name
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cloud # replace "mydatabase" with your database name
